### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by alex-saunders** [alex-saunders/ecmasyntax.io#10]
- [ ] Download all content now button 
- [ ] Remove all downloaded content button
- [ ] Move modals to more of a modal-manager style like with toasts
